[package]
name = "markflow"
version = "0.3.16"
description = "MarkFlow 文档转换工作台"
authors = ["MarkFlow"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
pathdiff = "0.2"
tauri-plugin-updater = "2.10.1"
tauri-plugin-process = "2.3.1"

[features]
# 默认编译时使用本地前端产物
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
panic = "abort"
